server:
  port: 8083

spring:
  application:
    name: file-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: file-storage

file:
  max-size: 524288000 # 500MB in bytes
  upload-path: files/
  allowed-types: 
    - pdf
    - doc
    - docx
    - xls
    - xlsx
    - ppt
    - pptx
    - txt
    - jpg
    - jpeg
    - png
    - gif
    - mp4
    - avi
    - mov
    - mkv
    - webm
    - flv

logging:
  level:
    org.library.fileservice: DEBUG
    io.minio: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/file-service.log

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health