# Liquibase configuration profile
# To use Liquibase instead of Flyway, activate this profile:
# spring.profiles.active=dev,liquibase

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: false
    contexts: ${spring.profiles.active}
  flyway:
    enabled: false