spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration 
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 60000ms

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

logging:
  level:
    root: WARN
    com.library: INFO