spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 60000ms

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

logging:
  level:
    root: WARN
    com.library: INFO